jwt:
  secret: test.test


spring:
  h2:
    console:
      enabled: true
      #path:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    driver-class-name: ${JDBC_DATABASE_DRIVER}