jwt:
  secret: test.test

spring:
  h2:
    console:
      enabled: true
      #path:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    #url: jdbc:h2:tcp://localhost/~/
    username: sa
    driver-class-name: org.h2.Driver