spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    logging.level:
      org.hibernate:
        SQL: debug
        type: trace
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    driver-class-name: ${DATABASE_DRIVER}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET_KEY}