name: Deploy to cloudtype
on:
  push:
    branches:
      - main, dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pon05114/jnuwiki
          stage: main
          yaml: >
            name: jnu-wiki-be

            app: java@17

            options:
              ports: 8080
              env:
                - name: JWT_SECRET_KEY
                  value: test.test
                - name: JDBC_DATABASE_URL
                  value: jdbc:mysql://mariadb:3306/jnuwiki?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
                - name: JDBC_DATABASE_USERNAME
                  value: cookie
                - name: JDBC_DATABASE_DRIVER
                  value: com.mysql.cj.jdbc.Driver
                - name: JDBC_DATABASE_PASSWORD
                  value: "04100410"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
